name: Generate Animations

on:
  schedule:
    - cron: "0 6 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: Generate 3D contrib & snake animation
    steps:
      - uses: actions/checkout@v4

      # 3D contribution graph
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: Shashank7016

      # Snake contribution animation
      - uses: Platane/snk/svg-only@v3
        with:
          github_user_name: Shashank7016
          outputs: |
            dist/github-snake.svg
            dist/github-snake-dark.svg?palette=github-dark

      - name: Commit & Push
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GH_PAT }}@github.com/${{ github.repository }}
          git add -A
          git diff --staged --quiet || git commit -m "Update profile animations"
          git push
